### ISSUE TITLE
Proxy Configuration does not work

### ISSUE THREAD

**Issue by ElmarKnipp** [nuxeo/nuxeo-cli#2]
I am using the latest verson 1.9.1 of ther toolkit. I have configured a proxy in my tcsh as follows:

`setenv http_proxy proxy.mycompany.de:8080`

Whenever a start the program, I get the following error:

```
/usr/lib/node_modules/nuxeo-cli/node_modules/global-tunnel-ng/lib/agents.js:17
  mixinProxying(this, opts.proxy);
                           ^

TypeError: Cannot read property 'proxy' of undefined
    at new OuterHttpAgent (/usr/lib/node_modules/nuxeo-cli/node_modules/global-tunnel-ng/lib/agents.js:17:28)
    at new ClientRequest (_http_client.js:126:13)
    at Object.request (http.js:46:10)
    at TunnelingAgent.request (/usr/lib/node_modules/nuxeo-cli/node_modules/global-tunnel-ng/index.js:336:40)
    at TunnelingAgent.createSocket (/usr/lib/node_modules/nuxeo-cli/node_modules/tunnel-agent/index.js:134:25)
    at TunnelingAgent.createSecureSocket [as createSocket] (/usr/lib/node_modules/nuxeo-cli/node_modules/tunnel-agent/index.js:199:41)
    at TunnelingAgent.createConnection (/usr/lib/node_modules/nuxeo-cli/node_modules/tunnel-agent/index.js:97:8)
    at TunnelingAgent.addRequest (/usr/lib/node_modules/nuxeo-cli/node_modules/tunnel-agent/index.js:91:8)
    at new ClientRequest (_http_client.js:302:16)
    at Object.request (https.js:310:10)
```

BTW: Why is a proxy configuration with protocol specification not made possible? The regular expression in `node_modules/nuxeo-cli/lib/proxy.js` seems to prohibit this: ` proxy.match(/^(?:([^@]+)@)?([^:]+)(?::(\d+))?$/);`

**Comment by mr-july** [comment]
The proxy configuration in `lib/proxy.js` can be simplified. There is no need to check and parse environment variables, because the library (`global-tunnel-ng`) respect the environment. So the whole proxy code could be simplified to
``` javascript
require('global-tunnel-ng').initialize();
```

But after that the problem is still not solved. The next proxy problem occur in another nuxeo module (`generator-nuxeo/generators/app/nuxeo-init-meta.js`). There the request
``` javascript
  // Ensure connection is up and cat reach github
  // In that case; update the metamodel from the repository
  // Otherwise try to find the latest fetch
  http.request({
    method: 'HEAD',
    host: 'www.github.com'
  }, (res) => {
    if (res.statusCode >= 500) {
      handleLocalClone(res);
    } else {
      handleRemoteClone();
    }
  }).on('error', (err) => {
    handleLocalClone(err);
  }).end();
```
could not be performed through proxy :-( and thus need to be changed, so the proxy configuration is taken into account.

But even if this problem is solved, then the next proxy problem occur in the `@octokit` module (`@octokit/request/dist-node/index.js`). This module uses the `node-fetch` module for requests and thus all configurations from `global-tunnel-ng` are just ignored. All requests will be made without proxy. :-(

So... After this all has been said, I would like to ask: **is the proxy support for `nuxeo-cli` just a declaration, which is not functional for a long time?**

Dear developers, please check if the proxy functionality is still repairable. And if not, please remove the proxy section from the README file or even better, please tell us frankly that **the proxy is not supported** at all in `nuxeo-cli`. In this way, users are at least saved time.

**Comment by akervern** [comment]
Thank you for this great deep analysis! 

We were looking for more feedback for this feature, and as you suggested; I'll remove the proxy part in the doc to avoid confusion until we fix the issue.

The `octokit` part shouldn't be a problem, it's not a mandatory dependency as the code relying on it can be rewritten to fetch tags using the HTTP API directly instead of relying on the library for it.

**Comment by ElmarKnipp** [comment]
Any update on this? Would be really nice to help corporate users behind a proxy.

Great thanks!
